name: Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python 3.11
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
          python3 -m pip install numpy==1.26.4
          python3 -m pip install pytest pytest-cov cython wheel 'jax>=0.9.1'
          python3 -m pip install kauri
          python3 -m pip install iisignature --no-build-isolation
          python3 -m pip install git+https://github.com/crispitagorico/sigkernel.git --no-build-isolation

      - name: Install package
        run: CUSIG=0 python -m pip install .

      - name: Run tests and collect coverage
        run: pytest --cov=pysiglib --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
